### ISSUE TITLE
Detecting missing letters?

### ISSUE THREAD

**Issue by gavv** [client9/misspell#56]
Does misspell detect typos with missing letters?

E.g. `confg` instead of `config`.

Is it in misspell scope? It would be very useful IMHO.

It's probably possible to generate all such typos statically, given a word list.

**Comment by client9** [comment]
Interesting idea.  Try it out!

http://app.aspell.net/create?max_size=60&spelling=US&max_variant=1&diacritic=both&download=wordlist&encoding=utf-8&format=inline

I suspect you'll find a few problems:

* The word lists don't contain very many technical words, include many common ones.
* Some words will be need to be rejected since it's ambiguous  (bad example: is `fll`  `full`, `fill`, or `fall`?)
* Some other words will need to be rejected since removing a letter turns it into a valid word
* The size! there are at least 100,000 words,   All combinations of missing letters, might be 500,000 entries.   To make that work, I think misspell would need to be implemented very differently.

The strategy misspell is using is "common misspellings" or "probable misspellings", not "all possible misspellings".

that said, I'm happy to take a look at any patch or pull request for this.

thanks!

n

**Comment by client9** [comment]
Hi @gavv  recently I added ~30,000 additional corrections.

let us know if it helps you.

n
